# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-15 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages_i18n', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatBlock_i18n',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('machine_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(blank=True)),
                ('template_name', models.CharField(blank=True, max_length=70)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'blocks',
                'ordering': ('title',),
                'verbose_name': 'block',
            },
        )
    ]
