# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages_i18n', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage_i18n',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flatpage_i18n',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
