# Generated by Django 3.1.14 on 2022-07-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages_i18n', '0002_auto_20200619_1344'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flatpage_i18n',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, machine_name=''), fields=('machine_name',), name='unique_machine_name'),
        ),
    ]
