# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages_i18n', '0002_auto_20170327_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='target',
            field=models.CharField(default='_self', max_length=7),
        )
    ]
